In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
#load the dataset
df=pd.read_csv("House_price_20k_dataset.csv")
df

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,DistanceToCity,LocationScore,Price
0,1260,2,1,2,1985,1.131558,4,703892
1,4172,2,3,1,1960,13.427760,7,1405741
2,3492,5,2,2,1952,25.732171,1,984664
3,866,1,3,2,1988,28.415415,3,289332
4,4826,2,1,3,1959,27.027016,5,862888
...,...,...,...,...,...,...,...,...
19995,4497,3,1,3,1982,27.871368,7,1064179
19996,4117,1,4,2,1969,7.306310,7,1633916
19997,4029,1,4,3,1997,29.803350,6,875527
19998,3153,5,2,3,2021,3.197826,8,1584736
19999,3767,3,4,1,2021,28.235279,9,1739842

In [3]:
#check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Area            20000 non-null  int64
 1   Bedrooms        20000 non-null  int64
 2   Bathrooms       20000 non-null  int64
 3   Floors          20000 non-null  int64
 4   YearBuilt       20000 non-null  int64
 5   DistanceToCity  20000 non-null  float64
 6   LocationScore   20000 non-null  int64
 7   Price           20000 non-null  int64
dtypes: float64(1), int64(7)
memory usage: 1.2 MB

In [4]:
#check null values
df.isnull().sum()

Area              0
Bedrooms          0
Bathrooms         0
Floors            0
YearBuilt         0
DistanceToCity    0
LocationScore     0
Price             0
dtype: int64

In [5]:
#check statistical analysis
df.describe()

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,DistanceToCity,LocationScore,Price
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,2.000000e+04
mean,2691.085250,3.028350,2.498950,1.990850,1986.283550,15.227126,5.498100,1.162495e+06
std,1320.913322,1.415538,1.116226,0.814678,21.303559,8.530603,2.882015,4.145436e+05
min,400.000000,1.000000,1.000000,1.000000,1950.000000,0.502977,1.000000,-6.536100e+04
25%,1544.750000,2.000000,2.000000,1.000000,1968.000000,7.763430,3.000000,8.661370e+05
50%,2688.500000,3.000000,2.000000,2.000000,1986.000000,15.341562,6.000000,1.157193e+06
75%,3826.000000,4.000000,3.000000,3.000000,2005.000000,22.631538,8.000000,1.449458e+06
max,4999.000000,5.000000,4.000000,3.000000,2023.000000,29.999765,10.000000,2.618112e+06

In [6]:
#checking outliers
numerical_colums=df.select_dtypes(include=["int64","float64"])
for col in numerical_columns:
    plt.figure(figsize=(5, 3))
    df.boxplot(column=col)
    plt.title(col)
    plt.show()

NameError: name 'numerical_columns' is not defined

In [8]:
#defining the X-independent variable and Y-dependent variable
X=df.drop(columns=["Price"])
y=df["Price"]
#splitting the training data and testing data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print("training data shape")
print("X_train shape :",X_train.shape)
print("y_train shape :",X_train.shape)
print("testing  data shape")
print("X_test shape :",X_train.shape)
print("y_test shape :",X_train.shape)

training data shape
X_train shape : (16000, 7)
y_train shape : (16000, 7)
testing  data shape
X_test shape : (16000, 7)
y_test shape : (16000, 7)

In [9]:
#scaling the data for better understanding  -1 to 1
scaling=StandardScaler()
X_train_scale=scaling.fit_transform(X_train)
X_test_scale=scaling.transform(X_test)

In [10]:
#train the model
model=LinearRegression()
model.fit(X_train_scale,y_train)

LinearRegression()

In [11]:
#model evalation
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = model.predict(X_test_scale)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 96982.57007291654
RMSE: 123281.18458966546
R²: 0.9116989509203496

In [15]:
#dumping the model
import pickle
with open("house_price_prediction.pkl","wb") as f:
    pickle.dump(model,f)
with open("scaling.pkl","wb") as f:
    pickle.dump(scaling,f)